version: '3'

services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    env_file:
      - .env  # Reference the .env file for environment variables
    volumes:
      - ./backend:/app  # Ensure backend is correctly mapped
    working_dir: /app  # Set the working directory to /app
    command: gunicorn backend.wsgi:application --bind 0.0.0.0:8000

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    env_file:
      - .env  # Reference the .env file for environment variables
