version: '3'

services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    env_file:
      - .env  # Reference the .env file for environment variables
    command: gunicorn backend.wsgi:application --bind 0.0.0.0:8000  # Added gunicorn command

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    env_file:
      - .env  # Reference the .env file for environment variables
