name: Deploy to EC2 (Ubuntu)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH to EC2
      uses: appleboy/ssh-action@v0.1.2
      with:
        host: 3.79.209.231  # Your EC2 public IP
        username: ubuntu  # Default username for Ubuntu EC2
        key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}  # SSH private key stored in GitHub Secrets
        port: 22
        script: |
          cd /home/ubuntu/stockmanagement
          git pull origin main
          sudo docker-compose down
          sudo docker-compose up -d
          sudo systemctl restart nginx
