name: Deploy to AWS EC2

on:
  push:
    branches:
      - main  # Or master, depending on your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Specify your Python version here

    - name: Install dependencies for the backend
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip
        pip install -r requirements.txt  # Backend dependencies

    - name: Install dependencies for frontend
      run: |
        npm install  # Frontend dependencies

    - name: Deploy to EC2 via SSH
      uses: appleboy/ssh-action@v0.1.2
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        port: 22
        script: |
          cd /path/to/your/app
          git pull origin main  # Pull latest changes from GitHub
          # You can restart your app here (if using Docker, for example)
          docker-compose up -d  # or use any other method to restart your backend/frontend
